### ISSUE TITLE
Plot config for assay types seems to be missing one

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/atlas-d2k-www#54]
https://dev.atlas-d2k.org/chaise/recordset/#2/Dashboard:Release_Status/*::facets::N4IghgdgJiBc[…]Dg2at2nHvyHCRQA@sort(Consortium,Species,ID::desc::)

This is the raw data. This shows 22 assay types. But the plot config for it to only shows 21: https://dev.atlas-d2k.org/deriva-webapps/plot/?config=all-data-summary

**Comment by jrchudy** [comment]
We are using a different query for this configuration in plot app than the query used for recordset. The query in plot app is filtering out any rows that don't have any released data. The `Imaging: Imaging Mass Cytometry (IMC)` assay has released = 0 when looking at recordset.

`https://dev.atlas-d2k.org/ermrest/catalog/2/entity/M:=Dashboard:Release_Status/Consortium=ALL/Species=ALL/!(Released=0)/$M@sort(ID::desc::)?limit=26`

This inconsistency can be seen when comparing with the home page also since that query (similar to recordset query) returns all 22 rows and counts them.
